version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:password@db:5432/jobboost
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRATION=1h
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobboost
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: